### PR TITLE
only use opendota

### PR DESCRIPTION
**Pull request by hsearcy**
Credit to @liboz for the match history piece in [#32](https://github.com/waylaidwanderer/DotaBuddy/pull/32)

Since 7.07 the Dota 2 API hasn't returned ranked matches from history, making this less than useful. @liboz made a change to use the opendota API to get match history. However, I found that I was still getting spotty results for some reason, so I made it pull the players from opendota, too.

This is a potential fix for [#31](https://github.com/waylaidwanderer/DotaBuddy/issues/31)

### CODE REVIEW

**Comment by liboz** [comment]
Maybe you ought to just remove the need for the steamapikey entirely. There's only 2 more calls one of which is matchdetails, which I believe opendota has as well.

**Comment by hsearcy** [comment]
I agree, I was just being lazy and didn't want to modify the UI. I might do so later, but for now I built this version on my local machine and am using it with decent results.

**Comment by hsearcy** [comment]
as per @liboz 's suggestion, I completely removed the steamAPI dependency. Everything seems to be working smoothly now.

**Comment by liboz** [comment]
@hsearcy Is there a reason you didn't remove the steam-api package dependence in package.json when recreating the commits I made?

**Comment by hsearcy** [comment]
@liboz Nope, I was just switching between operating systems so my package.json was getting whacky, so I didn't commit changes to it. I will pull it out of there shortly, but I'm going to try to see if using opendota allows more functionality to be easily added from data already pulled in.

**Pull request closed without merging**
